branches:
  only:
    - master
    - develop
language: objective-c

osx_image: xcode7.3

xcode_workspace: SwiftCamp.xcworkspace
xcode_scheme: SwiftCamp

before_install: 
  - brew update
  - gem install cocoapods -v '1.0.0'

script: xcodebuild -workspace SwiftCamp.xcworkspace -scheme SwiftCamp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO