branches:
  only:
    - master
    - develop
language: objective-c

osx_image: xcode7.3

before_install: 
  - brew update
  - brew upgrade xctool
  - gem upgrade cocoapods

script: xctool build -scheme SwiftCamp -sdk iphonesimulator9.2 -arch "i386" ONLY_ACTIVE_ARCH=NO VALID_ARCHS="i386 x86_64"